powsybl-ws-dependencies 2.7.0
powsybl/powsybl-network-conversion-server pull request #128
Opened 2024-01-30 16:24 UTC by antoinebhs

2024-01-31 10:46 UTC, antoinebhs commented on src/main/java/com/powsybl/network/conversion/server/GeneratorActivePowerControlSerDe.java
> + * @author Geoffroy Jamgotchian <geoffroy.jamgotchian at rte-france.com>
REMOVE HACK comment?

2024-01-31 12:02 UTC, etiennehomer requested changes

2024-01-31 12:02 UTC, etiennehomer commented on src/main/java/com/powsybl/network/conversion/server/GeneratorActivePowerControlSerDe.java
> +public class GeneratorActivePowerControlSerDe<T extends Injection<T>> extends AbstractExtensionSerDe<T, ActivePowerControl<T>> {
You should keep a comment saying that this class should be deleted later

2024-01-31 17:07 UTC, etiennehomer approved these changes

2024-01-31 17:09 UTC, antoinebhs commented
Find a comment to put on the duplicated classes from rte-core

2024-02-01 12:24 UTC, antoinebhs commented on src/main/java/com/powsybl/network/conversion/server/GeneratorActivePowerControlSerDe.java
> +        throw new IllegalStateException("Should never be called");
I agree with you but these 3 classes (GeneratorActivePowerControlSerDe.java, GeneratorShortCircuitsSerDe.java,VoltageLevelShortCircuitsSerDe.java) are duplicated from rte-core/iidm-cvg-extensions. I added a comment at the top of the file to make it clearer.
I think we should not change the message to be consistent with the private repository rte-core/iidm-cvg-extensions.

2024-02-01 19:19 UTC, AbdelHedhili approved these changes

2024-02-02 09:48 UTC, merged