[WIP] Indexing equipments in elasticsearch in parallel with flushing netwok and sending reports
powsybl/powsybl-network-conversion-server pull request #43
Opened 2021-09-16 07:47 UTC by SlimaneAmar

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Feature

**What is the current behavior?** *(You can also link to an open issue here)*
No Indexing equipments in Elasticsearch when network import

**What is the new behavior (if this is a feature change)?**
Indexing equipments when network import
Flushing network, sending reports and indexing in parallel

2021-09-23 06:16 UTC, geofjamg requested changes
Just minors cleanup!

2021-09-23 06:16 UTC, geofjamg commented on src/main/java/com/powsybl/network/conversion/server/NetworkConversionService.java
> +                    //.filter(Predicate.not(i -> i instanceof Switch))
To clean

2021-09-23 06:16 UTC, geofjamg commented on src/main/java/com/powsybl/network/conversion/server/NetworkConversionService.java
> +                    .parallelStream()
Is it really impacting performance?

2021-09-23 06:16 UTC, geofjamg commented on src/main/java/com/powsybl/network/conversion/server/elasticsearch/EquipmentInfosServiceMock.java
> +  Copyright (c) 2020, RTE (http://www.rte-france.com)
2021

2021-09-23 06:22 UTC, SlimaneAmar commented on src/main/java/com/powsybl/network/conversion/server/NetworkConversionService.java
> +                    //.filter(Predicate.not(i -> i instanceof Switch))
Done

2021-09-23 06:23 UTC, SlimaneAmar commented on src/main/java/com/powsybl/network/conversion/server/NetworkConversionService.java
> +                    .parallelStream()
Now with indexation in parallel no

2021-09-23 06:23 UTC, SlimaneAmar commented on src/main/java/com/powsybl/network/conversion/server/elasticsearch/EquipmentInfosServiceMock.java
> +  Copyright (c) 2020, RTE (http://www.rte-france.com)
Done

2021-09-27 06:40 UTC, geofjamg approved these changes

2021-09-27 07:01 UTC, merged