US #689 - equipments name search via elasticsearch to handle corner case characters
powsybl/powsybl-network-conversion-server pull request #54
Opened 2021-11-22 15:56 UTC by laurgarn

2021-12-28 10:00 UTC, SlimaneAmar requested changes

2021-12-28 10:00 UTC, SlimaneAmar commented on src/main/java/com/powsybl/network/conversion/server/dto/EquipmentInfos.java
>      String id;
Add the fullascii innerfield for id ?

2021-12-28 12:24 UTC, laurgarn commented on src/main/java/com/powsybl/network/conversion/server/dto/EquipmentInfos.java
>      String id;
Done

2021-12-30 09:41 UTC, laurgarn commented on src/main/java/com/powsybl/network/conversion/server/dto/EquipmentInfos.java
>      String id;
Done

2022-01-04 08:39 UTC, JacquesBorsenberger approved these changes

2022-01-04 09:29 UTC, SlimaneAmar approved these changes

2022-01-04 15:01 UTC, merged